// Generated by CoffeeScript 1.12.5
(function() {
  $('document').ready(function() {
    var skycons;
    var coordinates, error, options, roundTemp, skycons, success;
    error = function(err) {
      document.getElementById('loading').innerHTML = 'ERROR(' + err.code + '): ' + err.message;
    };
    success = function(pos) {
      var coordinates, crd;
      crd = pos.coords;
      coordinates = crd.latitude + ',' + crd.longitude;
      $.ajax({
        method: 'GET',
        url: 'https://maps.googleapis.com/maps/api/geocode/json',
        data: {
          key: 'AIzaSyA1Bu8-7_MDfT9oncmZ1KCjoz_2xdrTMFA',
          latlng: coordinates
        }
      }).done(function(data) {
        document.getElementById('currently-location').innerHTML = data.results['0'].address_components[3].short_name + ', ' + data.results['0'].address_components[5].short_name;
      });
      return $.ajax({
        method: 'GET',
        dataType: 'jsonp',
        url: "https://api.darksky.net/forecast/907160cda3c3fe28b8a7a2525b827ecc/" + coordinates + '?units=uk2'
      }).done(function(msg) {
        var roundTemp;
        skycons.add(document.getElementById('currently-icon'), msg.currently.icon);
        skycons.play();
        roundTemp = parseFloat(msg.currently.temperature).toFixed(0);
        document.getElementById('currently-summary').innerHTML = msg.currently.summary;
        document.getElementById('minutely-summary').innerHTML = msg.minutely.summary;
        document.getElementById('hourly-summary').innerHTML = msg.hourly.summary;
        document.getElementById('daily-summary').innerHTML = msg.daily.summary;
        document.getElementById('currently-temperature').innerHTML = roundTemp;
        document.getElementById('currently-temperature').style.display = 'inline';
        document.getElementById('currently-temp-unit').style.display = 'inline';
        document.getElementById('currently-icon').style.display = 'inline';
        document.getElementById('currently-summary').style.display = 'block';
        document.getElementById('minutely-summary').style.display = 'inline';
        document.getElementById('hourly-summary').style.display = 'block';
        document.getElementById('daily-summary').style.display = 'block';
        document.getElementById('currently-location').style.display = 'block';
        return document.getElementById('loading').style.display = 'none';
      });
    };
    coordinates = void 0;
    roundTemp = '0';
    skycons = new Skycons({
      'color': 'black'
    });
    if ('geolocation' in navigator) {
      options = {
        enableHighAccuracy: true,
        timeout: 5000,
        maximumAge: 0
      };
      navigator.geolocation.getCurrentPosition(success, error, options);
    } else {

      /* geolocation IS NOT available */
      alert('Sorry, your browser isn\'t providing a location.');
    }
  });

}).call(this);
